### PR TITLE
major overhaul

### PR DESCRIPTION
**Pull request by macmpi**
simple makefile to rebuild ovl package
embedded default network config for std cases
allow ethernet-usb gadget mode on pi-zero & al (just need to set dtoverlay=dwc2 in config.txt)
embed default ssh keys to expedite first boot (no key generation)
allow import of custom network parameters (interfaces/wpa_supplicant.conf)
self clean-up after boot so that setup-alpine can be executed clean

### CODE REVIEW

**Comment by macmpi** [comment]
Hope you can find it useful: let me know what you think.
If you don't feel comfortable to merge because too different approach, I may create a repo on my side as mentioned, and see how we can handle the wiki part.

**Comment by davidmytton** [comment]
Looks good. One minor comment. Will you also update the wiki?

**Comment by macmpi** [comment]
I can update the wiki accordingly, no problem.
We could keep a minimal version there and be more precise on this repo Readme?

**Comment by davidmytton** [comment]
> We could keep a minimal version there and be more precise on this repo Readme?

Looks good. Happy to merge when you're ready with the wiki updates.

**Comment by macmpi** [comment]
While at it, there is nothing that's so Pi-specific in there: it just works on any platform.
Why not calling it out Alpine-linux-headless, and referring to it in Pi setup pages and eventually others?

**Comment by davidmytton** [comment]
Sure - makes sense to me if it works on all platforms!

**Comment by macmpi** [comment]
it turns-out @sodface has created another Alpine wiki page on same matter for other platforms: https://wiki.alpinelinux.org/wiki/Unattended_Boot_and_Install
Would be nice to reconcile things maybe, and expose a single github script & instructions if we all agree.
We could merge-in the optional `unattended.sh` scripts execution in this github for exemple.

PI installation media setup is already described at length in other place, like https://wiki.alpinelinux.org/wiki/Raspberry_Pi
maybe just adding a headless section in there, with a link to updated headless bootstrap page would make sense?
Thoughts?

**Comment by sodface** [comment]
@macmpi I agree that consolidating functionality and documentation would be beneficial. There were a couple reasons I created another wiki page, both were in response to issues opened on Alpine's Gitlab:

https://gitlab.alpinelinux.org/alpine/aports/-/issues/13732
https://gitlab.alpinelinux.org/alpine/aports/-/issues/10119

I wanted to figure something (however hacky) out for unattended installs, and I also wanted to make it clearer that the headless boot stuff we are discussing here works on more than RPi's as you rightly noted above.

My original script scratched my itch at the time but it does seem like your PR accounts for more use cases and generally improves things across the board, though I haven't done any testing with it. A few comments/questions:

- Personal preference, but for something designed for a headless / unattended use case, using --quiet and sending stderr to /dev/null probably doesn't matter if no monitor is connected, and if a monitor is connected chances are it's because something went wrong and more output to terminal would be better than less.
- I would like to keep some form of unattended functionality. Could be a completely different approach or the same or an improved version of the other wiki I did. Although I usually end up with a solution that mostly works, I don't profess to be a shell script expert, and maybe not even a particularly good one, so input would be welcome.
- One thing I kind of wondered about but haven't tested was Windows line endings. Do you know if that's an issue or not with multi-line files like wpa_supplicant.conf? In other words, would a Windows user using notepad to create the files run into any issues? I used to be that Windows guy experimenting with RPi's on the side so I have some interest in not tripping them up or relying on Linux / non-native tools. That was the source of my objection to specifying that an ext4 partition needed to be created on the sd card. It's certainly helpful, but not required. A fat32 partition is all you need initally and probably all that most Windows users can do in this case.

**Comment by okuuva** [comment]
I've been playing around with this script for a few days and noticed the active discussion in this PR. So as a random Mac user I thought I'd add my two cents.

> Personal preference, but for something designed for a headless / unattended use case, using --quiet and sending stderr to /dev/null probably doesn't matter if no monitor is connected, and if a monitor is connected chances are it's because something went wrong and more output to terminal would be better than less.

I totally agree. Surpressing error logs is a bit counter productive in headless environments; they can be extremely useful when something goes wrong and don't really matter if everything works a-ok.

> I would like to keep some form of (optional) unattended functionality. Could be a completely different approach or the same or an improved version of the other wiki I did. Although I usually end up with a solution that mostly works, I don't profess to be a shell script expert, and maybe not even a particularly good one, so input would be welcome.

I've been writing and maintaining bash scripts as a big part of my day job for a few years now so I think I could be of some assistance if needed.

> I have some interest in not tripping them [Windows users] up or relying on Linux / non-Windows-native tools. That was the source of my objection to specifying that an ext4 partition needed to be created on the sd card. It's certainly helpful, but not required. A fat32 partition is all you need initally and probably all that most Windows users can do in this case.

Can't attest to Windows users but as at least with Mac afaik you can't create ext4 partition without buying extFS from Paragon software.

**Comment by macmpi** [comment]
> * I would like to keep some form of (optional) unattended functionality.

will include the optional `unattended .sh`

> * A fat32 partition is all you need initally

Agreed: this is not really linked to the script itself, but about the wiki documentation.
I think the headless-bootstrap instructions should not get into the media setup & partitioning thing: it just comes after existing install guides (probably just insert a heading with link to new headless-bootstrap page), and whatever platforms.

> Suppressing error logs is a bit counter productive in headless environments

ok will change that, and let errors messages flow

> * One thing I kind of wondered about but haven't tested was Windows [/Mac]  line endings.

we could eventually add some sed trick on importing external files, but one would really expect from users getting into Alpine install to most probably use some advanced Windows/Mac editors  (notepad++/BBEdit and al.) that care about that CR/LF issues.

> * @davidmytton Is a PR now the only way to provide feedback?

if traffic here feels too uncomfortable, I can host the whole thing with issues on my github.

**Comment by sodface** [comment]
> okuuva: I've been writing and maintaining bash scripts as a big part of my day job for a few years now so I think I could be of some assistance if needed.

The more review and input the better. The line ending thing I mentioned was sort of silly of me to bring up, and as macmpi seems to imply, most likely a non-issue. Just a thought I had when working on the unattended.sh stuff - "am I inadvertently making things difficult on Windows users?" I haven't used Mac at all and assumed most things would work as-is so the ext4 issue you mentioned surprises me.

Some more thoughts I had that I've been meaning to come back to:
- The CR/LF thing, probably easy to test/fix with the unix2dos and dos2unix busybox applets but I just haven't done it.
- For the unattended.sh specifically, I copy the file to a tmp file because opening it directly from the ovlpath makes that mount busy, at least on my testing with a pi4, preventing you from from installing to sd card with setup-disk.
- Again for unattended.sh, using the `source` command in root's .profile I now know is not POSIX whereas `.` is, I just thought `source` was more self documenting and is included with Alpine's busybox ash so there's no issue with availability until maybe when Alpine changes the default shell, which they've been talking about.
-  Sourcing the file and even assuming it's a shell script may not be the best choice, though it's easy I suppose to just minimally use unattended.sh to `apk add` your language/utility of choice and continue on from there. Another option would be to introduce another optional file `extra.apks` or something that headless.start could read and add automatically.

> macmpi: I think the headless-bootstrap instructions should not get into the media setup & partitioning thing

Agree, better to point to existing documentation.

> macmpi: if traffic here feels too uncomfortable, I can host the whole thing with issues on my github.

Nothing personal against davidmytton, I think his effort here was the right thing to do, but there were several issue comments that went unresponded to for awhile and they seem to have since disappeared altogether.  I can only assume that time constraints on his part were the driver to removing them, but he was responsive to your PR so maybe I'm off-base. I have no preference (not that it would matter if I did) on where its hosted and will most likely take down my hosted files and wiki references after functionality is merger, wherever that ends up being.

**Comment by macmpi** [comment]
ok, will set it up on my github then in the next 1-2 days: will close this PR when ready.

**Comment by macmpi** [comment]
it's up there https://github.com/macmpi/alpine-linux-headless-bootstrap

**Comment by davidmytton** [comment]
Will do, thanks!

**Pull request closed without merging**
